server {
    listen 80;
    listen [::]:80;
    server_name teacher.superwhys.top;

	gzip on;
    gzip_types text/plain text/css application/javascript application/json application/xml image/svg+xml;
    gzip_min_length 1024;

    root /etc/nginx/www/teacher.superwhys.top;
    index index.html index.htm;

    access_log /etc/nginx/logs/teacher.access.log;
    error_log  /etc/nginx/logs/teacher.error.log warn;

    location ~* \.(?:css|js|mjs|json|png|jpg|jpeg|gif|webp|svg|ico|ttf|otf|woff|woff2)$ {
        expires 7d;
        add_header Cache-Control "public, max-age=604800, immutable";
        try_files $uri =404;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
