/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionItem: typeof import('./components/ActionItem.vue')['default']
    AddStudentDialog: typeof import('./components/class/AddStudentDialog.vue')['default']
    AnimatedCharacters: typeof import('./components/login/AnimatedCharacters.vue')['default']
    BaseCard: typeof import('./components/BaseCard.vue')['default']
    ClassBottomActions: typeof import('./components/class/ClassBottomActions.vue')['default']
    ClassStudentList: typeof import('./components/class/ClassStudentList.vue')['default']
    EditStudentDialog: typeof import('./components/class/EditStudentDialog.vue')['default']
    ExportPointsButton: typeof import('./components/points/ExportPointsButton.vue')['default']
    GroupImportDialog: typeof import('./components/class/GroupImportDialog.vue')['default']
    GroupManageDialog: typeof import('./components/class/GroupManageDialog.vue')['default']
    ImportPointsButton: typeof import('./components/points/ImportPointsButton.vue')['default']
    LoginAnimationExample: typeof import('./components/login/LoginAnimationExample.vue')['default']
    LotteryView: typeof import('./components/tools/LotteryView.vue')['default']
    PointsBottomActions: typeof import('./components/points/PointsBottomActions.vue')['default']
    PointsHeaderActionsPanel: typeof import('./components/points/PointsHeaderActionsPanel.vue')['default']
    PointsHistoryButton: typeof import('./components/points/PointsHistoryButton.vue')['default']
    PointsImportItemsButton: typeof import('./components/points/PointsImportItemsButton.vue')['default']
    PointsManageItemsButton: typeof import('./components/points/PointsManageItemsButton.vue')['default']
    PointsRankingCard: typeof import('./components/points/PointsRankingCard.vue')['default']
    PointsRankingPanel: typeof import('./components/points/PointsRankingPanel.vue')['default']
    PointsRuleManageDialog: typeof import('./components/points/PointsRuleManageDialog.vue')['default']
    PointsRuleRankingCard: typeof import('./components/points/PointsRuleRankingCard.vue')['default']
    PointsRuleSelectorDialog: typeof import('./components/points/PointsRuleSelectorDialog.vue')['default']
    PointsStudentList: typeof import('./components/points/PointsStudentList.vue')['default']
    RollCallView: typeof import('./components/tools/RollCallView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShopExchangeDialog: typeof import('./components/shop/ShopExchangeDialog.vue')['default']
    ShopHeaderRow: typeof import('./components/shop/ShopHeaderRow.vue')['default']
    ShopImportDialog: typeof import('./components/shop/ShopImportDialog.vue')['default']
    ShopPrizeEditorDialog: typeof import('./components/shop/ShopPrizeEditorDialog.vue')['default']
    ShopPrizeGrid: typeof import('./components/shop/ShopPrizeGrid.vue')['default']
    ShopRecordsTable: typeof import('./components/shop/ShopRecordsTable.vue')['default']
    ShopToolbar: typeof import('./components/shop/ShopToolbar.vue')['default']
    TimerView: typeof import('./components/tools/TimerView.vue')['default']
    ToolCard: typeof import('./components/ToolCard.vue')['default']
  }
}
